name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: set_var
        run: |
          version=`cat ./android/app/build.gradle | grep versionName | xargs | cut -d' ' -f2`
          echo $version
          echo "::set-output name=version::$version"

      - name: Install yarn dependencies
        run: |
          yarn install

      - name: Build Android Release
        run: |
          cd android && chmod +x gradlew && ./gradlew assembleRelease

      - name: Auto tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: apk.zip
          path: android/app/build/outputs/apk/release/

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: android/app/build/outputs/apk/release/
          remote: uploads
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          port: ${{ secrets.PORT }}

      - name: Discord Webhook
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: "Le Livreur d'APKs"
          color: '#3DDC84'
          avatarUrl: 'https://cdn.discordapp.com/attachments/272639040434601994/737049367877386260/android-flat.png'
          description: "Numéro de version: ${{ steps.set_var.outputs.version }}"
          details: |
            **Télécharge-la ici :**
            - [universal apk](https://cdn.becauseofprog.fr/v2/sites/becauseofprog.fr/app/app-universal-release.apk)
            - [armeabi-v7a](https://cdn.becauseofprog.fr/v2/sites/becauseofprog.fr/app/app-armeabi-v7a-release.apk)
            - [arm64-v8a](https://cdn.becauseofprog.fr/v2/sites/becauseofprog.fr/app/app-arm64-v8a-release.apk)
            - [app-x86_64-release](https://cdn.becauseofprog.fr/v2/sites/becauseofprog.fr/app/app-x86_64-release.apk)
            - [app-x86-release](https://cdn.becauseofprog.fr/v2/sites/becauseofprog.fr/app/app-x86-release.apk)

            Quoi de nouveau : [changelog](https://github.com/BecauseOfProg/app/blob/master/changelog.md)

            Plus d'infos : [ici](https://play.google.com/store/apps/details?id=com.ytheekshana.deviceinfo)
          footer: APK Android
          text: "<:becauseofprog:308300785991680000> Nouvelle version de l'app **BecauseOfProg** *(Android)* ! :tada:"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          args: |
            *Nouvelle version* (${{ steps.set_var.outputs.version }}) de l'application *Android* disponible !
            Télécharge-la ici :
            - [universal apk](https://cdn.becauseofprog.fr/v2/sites/becauseofprog.fr/app/app-universal-release.apk)
            - [armeabi-v7a](https://cdn.becauseofprog.fr/v2/sites/becauseofprog.fr/app/app-armeabi-v7a-release.apk)
            - [arm64-v8a](https://cdn.becauseofprog.fr/v2/sites/becauseofprog.fr/app/app-arm64-v8a-release.apk)
            - [Autres](https://becauseofprog.fr/page/app)

            Quoi de nouveau : [changelog](https://github.com/BecauseOfProg/app/blob/master/changelog.md)
          document: android/app/build/outputs/apk/release/app-universal-release.apk
