name: react-native-android-dev
on:
  push:
    branches:
      - dev
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install

      - name: Build Android Release
        run: |
          cd android && chmod +x gradlew && ./gradlew assembleRelease
